import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header, TopNavItem } from "@/components/layout/Header";

const TOP_NAV_ITEMS: TopNavItem[] = [
  { id: "home", label: "HOME", href: "/", isActive: true },
  { id: "vault", label: "VAULT", href: "#", isActive: false },
  { id: "mylist", label: "MY LIST", href: "#", isActive: false },
  { id: "activity", label: "ACTIVITY", href: "#", isActive: false },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <Header logoText="DREADBASE" navItems={TOP_NAV_ITEMS} searchPlaceholder="SEARCH..." />
        {children}
      </body>
    </html>
  );
}
